// Email notifications via Postmark (account approved).
// The f-1careers.com domain is verified in Postmark (DKIM + Return-Path), so we can
// send from any address on it. Set in Vercel env vars:
//   POSTMARK_SERVER_TOKEN  the Server API token
//   FROM_EMAIL             e.g. "F-1 Careers <support@f-1careers.com>"

const POSTMARK_SERVER_TOKEN = process.env.POSTMARK_SERVER_TOKEN
const FROM_EMAIL = process.env.FROM_EMAIL ?? 'F-1 Careers <support@f-1careers.com>'
const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://www.f-1careers.com'

async function sendEmail(to: string, subject: string, html: string): Promise<string> {
  if (!POSTMARK_SERVER_TOKEN) {
    console.log('[email] POSTMARK_SERVER_TOKEN not set, skipping email to', to)
    return 'skipped:no-token'
  }

  const res = await fetch('https://api.postmarkapp.com/email', {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Content-Type': 'application/json',
      'X-Postmark-Server-Token': POSTMARK_SERVER_TOKEN,
    },
    body: JSON.stringify({
      From: FROM_EMAIL,
      To: to,
      Subject: subject,
      HtmlBody: html,
      MessageStream: 'outbound',
    }),
  })

  if (!res.ok) {
    const err = await res.text()
    console.error('[email] Postmark error:', res.status, err)
    return `error ${res.status}: ${err}`
  }
  console.log('[email] Sent to', to, '-', subject)
  return 'sent'
}

// ─── Email templates ──────────────────────────────────────────────

export async function sendStrategyReportReady(to: string, reportId: string) {
  const reportUrl = `${APP_URL}/strategy/report/${reportId}`

  await sendEmail(
    to,
    'Your Career Strategy Report is ready',
    `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f6fb;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(27,43,107,0.10);">

    <!-- Header -->
    <div style="background:#1B2B6B;padding:32px 36px 28px;">
      <div style="display:flex;align-items:center;gap:8px;">
        <span style="font-size:20px;font-weight:800;color:white;letter-spacing:-0.5px;">F-1 Careers</span>
      </div>
    </div>

    <!-- Body -->
    <div style="padding:36px;">
      <h1 style="font-size:22px;font-weight:700;color:#1B2B6B;margin:0 0 12px;">Your Career Strategy Report is ready</h1>
      <p style="color:#555566;font-size:15px;line-height:1.6;margin:0 0 24px;">
        Your full career and immigration strategy report has been generated. It includes your visa pathway assessment, criterion-by-criterion EB-1A and NIW analysis, evidence mapping, gap analysis, and your personalized 12-month roadmap.
      </p>

      <a href="${reportUrl}" style="display:inline-block;background:#00C2A8;color:white;font-weight:700;font-size:15px;padding:14px 28px;border-radius:12px;text-decoration:none;margin-bottom:28px;">
        View your report →
      </a>

      <div style="border-top:1px solid #DEDEDE;padding-top:20px;margin-top:4px;">
        <p style="color:#888;font-size:12px;line-height:1.6;margin:0;">
          This report was generated by F-1 Careers and does not constitute legal advice.
          Please consult a licensed immigration attorney before filing any petition.
        </p>
      </div>
    </div>
  </div>
</body>
</html>`,
  )
}

export async function sendRFEReportReady(to: string, reportId: string, caseType: string) {
  const reportUrl = `${APP_URL}/rfe/report/${reportId}`

  await sendEmail(
    to,
    'Your RFE Response Analysis is ready',
    `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f6fb;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(27,43,107,0.10);">

    <!-- Header -->
    <div style="background:#1B2B6B;padding:32px 36px 28px;">
      <div style="display:flex;align-items:center;gap:8px;">
        <span style="font-size:20px;font-weight:800;color:white;letter-spacing:-0.5px;">F-1 Careers</span>
      </div>
    </div>

    <!-- Body -->
    <div style="padding:36px;">
      <h1 style="font-size:22px;font-weight:700;color:#1B2B6B;margin:0 0 12px;">Your RFE Analysis is ready</h1>
      <p style="color:#555566;font-size:15px;line-height:1.6;margin:0 0 8px;">
        <strong style="color:#1B2B6B;">Case:</strong> ${caseType || 'RFE Analysis'}
      </p>
      <p style="color:#555566;font-size:15px;line-height:1.6;margin:0 0 24px;">
        Your issue-by-issue RFE response strategy is complete. Every USCIS concern is identified, risk-ranked, and paired with a specific response strategy and evidence checklist. Share this directly with your attorney.
      </p>

      <a href="${reportUrl}" style="display:inline-block;background:#1B2B6B;color:white;font-weight:700;font-size:15px;padding:14px 28px;border-radius:12px;text-decoration:none;margin-bottom:28px;">
        View your RFE analysis →
      </a>

      <div style="border-top:1px solid #DEDEDE;padding-top:20px;margin-top:4px;">
        <p style="color:#888;font-size:12px;line-height:1.6;margin:0;">
          This analysis is a strategic planning tool and does not constitute legal advice.
          Work with a licensed immigration attorney to prepare and file your RFE response.
        </p>
      </div>
    </div>
  </div>
</body>
</html>`,
  )
}

// Internal notification (to the founder) when a user requests an attorney review.
export async function sendAttorneyReviewRequest(opts: {
  userEmail: string
  reportType: string
  reportId: string
  consentShare: boolean
  note?: string
}): Promise<string> {
  const to = process.env.ATTORNEY_NOTIFY_EMAIL ?? 'support@f-1careers.com'
  const reportUrl = `${APP_URL}/${opts.reportType}/report/${opts.reportId}`
  return await sendEmail(
    to,
    `Attorney review requested, ${opts.userEmail}`,
    `<!DOCTYPE html><html><body style="font-family:system-ui,sans-serif;color:#1B2B6B;">
      <h2 style="margin:0 0 12px;">New attorney review request</h2>
      <p style="margin:4px 0;"><strong>User:</strong> ${opts.userEmail}</p>
      <p style="margin:4px 0;"><strong>Report:</strong> ${opts.reportType} (${opts.reportId})</p>
      <p style="margin:4px 0;"><strong>Consent to share report:</strong> ${opts.consentShare ? 'Yes' : 'No'}</p>
      ${opts.note ? `<p style="margin:4px 0;"><strong>Note:</strong> ${opts.note}</p>` : ''}
      <p style="margin:16px 0 4px;"><a href="${reportUrl}" style="color:#00C2A8;font-weight:700;">Open the report &rarr;</a></p>
      <p style="color:#888;font-size:12px;margin-top:16px;">Follow up by connecting them with a vetted independent attorney. Do not share the report without the consent flag above.</p>
    </body></html>`,
  )
}
