// Email notifications via Google Workspace SMTP (nodemailer).
// Auth uses an App Password for the Workspace mailbox (requires 2-Step
// Verification on that account). Set these in .env.local + Vercel env vars:
//   SMTP_USER  e.g. support@f-1careers.com
//   SMTP_PASS  the 16-char Google App Password (no spaces)
//   FROM_EMAIL e.g. "F-1 Careers <support@f-1careers.com>" (must match/alias SMTP_USER)
import nodemailer from 'nodemailer'

const SMTP_USER = process.env.SMTP_USER
const SMTP_PASS = process.env.SMTP_PASS
const FROM_EMAIL = process.env.FROM_EMAIL ?? 'F-1 Careers <support@f-1careers.com>'
const APP_URL = process.env.NEXT_PUBLIC_APP_URL ?? 'https://www.f-1careers.com'

// Reuse a single transporter across invocations. Gmail/Workspace SMTP over
// implicit TLS (port 465). App Passwords strip any spaces.
const transporter =
  SMTP_USER && SMTP_PASS
    ? nodemailer.createTransport({
        host: 'smtp.gmail.com',
        port: 465,
        secure: true,
        auth: { user: SMTP_USER, pass: SMTP_PASS.replace(/\s+/g, '') },
      })
    : null

async function sendEmail(to: string, subject: string, html: string) {
  if (!transporter) {
    console.log('[email] SMTP_USER/SMTP_PASS not set, skipping email to', to)
    return
  }

  try {
    await transporter.sendMail({ from: FROM_EMAIL, to, subject, html })
    console.log('[email] Sent to', to, '—', subject)
  } catch (err) {
    console.error('[email] SMTP error:', err)
  }
}

// ─── Email templates ──────────────────────────────────────────────

export async function sendStrategyReportReady(to: string, reportId: string) {
  const reportUrl = `${APP_URL}/strategy/report/${reportId}`

  await sendEmail(
    to,
    'Your Career Strategy Report is ready',
    `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f6fb;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(27,43,107,0.10);">

    <!-- Header -->
    <div style="background:#1B2B6B;padding:32px 36px 28px;">
      <div style="display:flex;align-items:center;gap:8px;">
        <span style="font-size:20px;font-weight:800;color:white;letter-spacing:-0.5px;">F-1 Careers</span>
        <span style="font-size:11px;font-weight:700;color:#00C2A8;background:rgba(0,194,168,0.15);padding:2px 8px;border-radius:6px;border:1px solid rgba(0,194,168,0.3);">AI</span>
      </div>
    </div>

    <!-- Body -->
    <div style="padding:36px;">
      <h1 style="font-size:22px;font-weight:700;color:#1B2B6B;margin:0 0 12px;">Your Career Strategy Report is ready</h1>
      <p style="color:#555566;font-size:15px;line-height:1.6;margin:0 0 24px;">
        Your full career and immigration strategy report has been generated. It includes your visa pathway assessment, criterion-by-criterion EB-1A and NIW analysis, evidence mapping, gap analysis, and your personalized 12-month roadmap.
      </p>

      <a href="${reportUrl}" style="display:inline-block;background:#00C2A8;color:white;font-weight:700;font-size:15px;padding:14px 28px;border-radius:12px;text-decoration:none;margin-bottom:28px;">
        View your report →
      </a>

      <div style="border-top:1px solid #DEDEDE;padding-top:20px;margin-top:4px;">
        <p style="color:#888;font-size:12px;line-height:1.6;margin:0;">
          This report was generated by F-1 Careers AI and does not constitute legal advice.
          Please consult a licensed immigration attorney before filing any petition.
        </p>
      </div>
    </div>
  </div>
</body>
</html>`,
  )
}

export async function sendRFEReportReady(to: string, reportId: string, caseType: string) {
  const reportUrl = `${APP_URL}/rfe/report/${reportId}`

  await sendEmail(
    to,
    'Your RFE Response Analysis is ready',
    `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head>
<body style="margin:0;padding:0;background:#f4f6fb;font-family:system-ui,-apple-system,sans-serif;">
  <div style="max-width:560px;margin:40px auto;background:white;border-radius:16px;overflow:hidden;box-shadow:0 4px 24px rgba(27,43,107,0.10);">

    <!-- Header -->
    <div style="background:#1B2B6B;padding:32px 36px 28px;">
      <div style="display:flex;align-items:center;gap:8px;">
        <span style="font-size:20px;font-weight:800;color:white;letter-spacing:-0.5px;">F-1 Careers</span>
        <span style="font-size:11px;font-weight:700;color:#00C2A8;background:rgba(0,194,168,0.15);padding:2px 8px;border-radius:6px;border:1px solid rgba(0,194,168,0.3);">AI</span>
      </div>
    </div>

    <!-- Body -->
    <div style="padding:36px;">
      <h1 style="font-size:22px;font-weight:700;color:#1B2B6B;margin:0 0 12px;">Your RFE Analysis is ready</h1>
      <p style="color:#555566;font-size:15px;line-height:1.6;margin:0 0 8px;">
        <strong style="color:#1B2B6B;">Case:</strong> ${caseType || 'RFE Analysis'}
      </p>
      <p style="color:#555566;font-size:15px;line-height:1.6;margin:0 0 24px;">
        Your issue-by-issue RFE response strategy is complete. Every USCIS concern is identified, risk-ranked, and paired with a specific response strategy and evidence checklist. Share this directly with your attorney.
      </p>

      <a href="${reportUrl}" style="display:inline-block;background:#1B2B6B;color:white;font-weight:700;font-size:15px;padding:14px 28px;border-radius:12px;text-decoration:none;margin-bottom:28px;">
        View your RFE analysis →
      </a>

      <div style="border-top:1px solid #DEDEDE;padding-top:20px;margin-top:4px;">
        <p style="color:#888;font-size:12px;line-height:1.6;margin:0;">
          This analysis is a strategic planning tool and does not constitute legal advice.
          Work with a licensed immigration attorney to prepare and file your RFE response.
        </p>
      </div>
    </div>
  </div>
</body>
</html>`,
  )
}
