/**
 * POST /api/petition-builder/download
 * ─────────────────────────────────────────────
 * Generates a downloadable RTF document from the petition package.
 * RTF is a pure-text format that Word, Google Docs, and Pages all
 * open natively — no npm packages required.
 *
 * Accepts: { docType: 'statement' | 'cover' | 'package', packet: PetitionPackage }
 */

import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

function escapeRtf(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/\{/g, '\\{')
    .replace(/\}/g, '\\}')
    .replace(/\n\n/g, '\\par\\par ')
    .replace(/\n/g, '\\par ')
}

function textToRtf(title: string, content: string): string {
  const lines = content.split('\n')
  let body = ''

  for (const line of lines) {
    const trimmed = line.trim()

    // All-caps lines that look like section headers
    if (trimmed && trimmed === trimmed.toUpperCase() && trimmed.length > 3 && trimmed.length < 80) {
      body += `\\pard\\sb240\\sa120\\b\\fs24 ${escapeRtf(trimmed)}\\b0\\par\n`
    }
    // Lines starting with bold-style markers (e.g., "Prong 1:", "Exhibit A:")
    else if (trimmed.match(/^(Prong|Criterion|Exhibit|Section|Part)\s+\w+[:\-]/i)) {
      body += `\\pard\\sb180\\sa60\\b ${escapeRtf(trimmed)}\\b0\\par\n`
    }
    // Empty line — paragraph break
    else if (!trimmed) {
      body += '\\pard\\sa120\\par\n'
    }
    // Normal paragraph
    else {
      body += `\\pard\\sa120\\fi0 ${escapeRtf(trimmed)}\\par\n`
    }
  }

  return `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0\\froman\\fcharset0 Times New Roman;}{\\f1\\fswiss\\fcharset0 Arial;}}
{\\colortbl ;\\red20\\green30\\blue60;}
\\paperw12240\\paperh15840\\margl1440\\margr1440\\margt1440\\margb1440
\\f0\\fs24
\\pard\\qc\\sb360\\sa180\\b\\fs32\\cf1 ${escapeRtf(title)}\\b0\\par
\\pard\\sb0\\sa0\\f1\\fs18\\cf1 Generated by F-1 Careers Petition Builder · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })} · Review with an immigration attorney before filing.\\par
\\pard\\sb0\\sa0\\brdrb\\brdrs\\brdrw10\\brsp20 \\par
${body}
}`
}

function packageToRtf(statement: string, coverLetter: string, pathway: string): string {
  const statementRtf = statement.split('\n').map(line => {
    const trimmed = line.trim()
    if (!trimmed) return '\\pard\\sa120\\par\n'
    if (trimmed === trimmed.toUpperCase() && trimmed.length > 3 && trimmed.length < 80) {
      return `\\pard\\sb240\\sa120\\b\\fs24 ${escapeRtf(trimmed)}\\b0\\par\n`
    }
    if (trimmed.match(/^(Prong|Criterion|Exhibit|Section|Part)\s+\w+[:\-]/i)) {
      return `\\pard\\sb180\\sa60\\b ${escapeRtf(trimmed)}\\b0\\par\n`
    }
    return `\\pard\\sa120 ${escapeRtf(trimmed)}\\par\n`
  }).join('')

  const coverRtf = coverLetter.split('\n').map(line => {
    const trimmed = line.trim()
    if (!trimmed) return '\\pard\\sa120\\par\n'
    if (trimmed.match(/^Exhibit\s+[A-Z]:/i) || trimmed.match(/^(COVER LETTER|PERSONAL STATEMENT)/i)) {
      return `\\pard\\sb180\\sa60\\b ${escapeRtf(trimmed)}\\b0\\par\n`
    }
    return `\\pard\\sa120 ${escapeRtf(trimmed)}\\par\n`
  }).join('')

  const disclaimer = 'IMPORTANT: This document was generated by AI for informational purposes only. It is not legal advice. Review all content carefully and have an immigration attorney review before filing. Replace any bracketed placeholders with your specific information.'

  return `{\\rtf1\\ansi\\deff0
{\\fonttbl{\\f0\\froman\\fcharset0 Times New Roman;}{\\f1\\fswiss\\fcharset0 Arial;}}
{\\colortbl ;\\red20\\green30\\blue60;\\red180\\green60\\blue0;}
\\paperw12240\\paperh15840\\margl1440\\margr1440\\margt1440\\margb1440
\\f0\\fs24
\\pard\\qc\\sb360\\sa120\\b\\fs36\\cf1 Petition Package\\b0\\par
\\pard\\qc\\sa60\\f1\\fs20\\cf1 ${escapeRtf(pathway === 'NIW' ? 'EB-2 National Interest Waiver (NIW)' : 'EB-1A Extraordinary Ability')} · ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}\\par
\\pard\\sb240\\sa120\\b\\fs22\\cf2 ${escapeRtf(disclaimer)}\\b0\\par
\\pard\\sb360\\sa120\\brdrb\\brdrs\\brdrw15\\brsp20\\b\\fs30\\cf1 PERSONAL STATEMENT\\b0\\par
${statementRtf}
\\pard\\sb480\\sa120\\brdrt\\brdrs\\brdrw15\\brsp20\\brdrb\\brdrs\\brdrw15\\brsp20\\b\\fs30\\cf1 COVER LETTER\\b0\\par
${coverRtf}
}`
}

export async function POST(req: Request) {
  try {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return new NextResponse('Unauthorized', { status: 401 })

    const { docType, packet } = await req.json()

    if (!packet) return new NextResponse('No petition package provided', { status: 400 })

    let rtfContent: string
    let filename: string

    if (docType === 'statement') {
      rtfContent = textToRtf('Personal Statement', packet.personal_statement)
      filename = `personal-statement-${packet.pathway.toLowerCase()}.rtf`
    } else if (docType === 'cover') {
      rtfContent = textToRtf('Cover Letter', packet.cover_letter)
      filename = `cover-letter-${packet.pathway.toLowerCase()}.rtf`
    } else {
      // Full package
      rtfContent = packageToRtf(packet.personal_statement, packet.cover_letter, packet.pathway)
      filename = `petition-package-${packet.pathway.toLowerCase()}.rtf`
    }

    return new NextResponse(rtfContent, {
      status: 200,
      headers: {
        'Content-Type': 'application/rtf',
        'Content-Disposition': `attachment; filename="${filename}"`,
      },
    })
  } catch (error) {
    console.error('[petition-download]', error)
    return new NextResponse('Failed to generate document', { status: 500 })
  }
}
